
apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainingRuntime
metadata:
  name: prepare-data-runtime
  namespace: training # Or the namespace where your runtime will live
spec:
  template:
    metadata:
      name: prepare-data-runtime
      namespace: training
    spec:
      replicatedJobs:
        - name: prepare-data-rj
          template:
            metadata:
              name: prepare-data-rj
              namespace: training
            spec:
              parallelism: 1
              template:
                metadata: 
                  name: prepare-data-pod
                  namespace: training
                spec:
                  containers:
                    - image: snpsuen/call_train_lib:02
                      imagePullPolicy: IfNotPresent
                      name: prepare-data-container
                      command: ["python", "/workspace/call_prepare_data.py"]
                      volumeMounts:
                        - name: pytorch-vol
                          mountPath: /pytorch
                  nodeName: kfp-control-plane
                  volumes:
                    - name: pytorch-vol
                      hostPath:
                        path: /var/tmp/pytorch
                        type: DirectoryOrCreate
---
apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: prepare-data-job
  namespace: training # Or the namespace where your runtime will live
spec:
  runtimeRef:
    kind: TrainingRuntime
    name: prepare-data-runtime
