FROM python:3.10-slim

ENV KUBECTL_VERSION=v1.30.1

# Install dependencies and kubectl
RUN apt-get update && apt-get install -y curl ca-certificates && \
    curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
