apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trainjob-crd-access
rules:
  - apiGroups: ["trainer.kubeflow.org"]
    resources: ["trainjobs", "trainingruntimes"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-pipeline-runner-to-create-traincrd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trainjob-crd-access
subjects:
- kind: ServiceAccount
  name: pipeline-runner
  namespace: kubeflow
